name: my_env  # 你可以改成你的环境名，比如 pytorch-2.1.2
channels:
  - conda-forge # 优先使用 conda-forge channel
  - defaults
dependencies:
  # --- Conda Packages ---
  # 确保这些核心库由 Conda 管理
  - lightgbm        # Conda 会从 conda-forge 安装，可能包含 GPU 支持
  - numpy
  - pandas
  - scikit-learn
  - scipy           # 明确添加 scipy，解决之前的 GLIBCXX 错误
  - libstdcxx-ng    # (可选但推荐) 明确指定 Conda 管理的 C++ 库
  # - 其他你想用 Conda 安装的包... 例如:
  # - matplotlib
  # - seaborn
  # - joblib # 如果需要保存模型

  # --- Pip Packages ---
  - pip
  - pip:
      # 这里的 requirements.txt 只应包含 Conda channels 中没有的，
      # 或者你必须使用特定 pip 版本的包。
      # !!! 确保 requirements.txt 中没有重复上面 Conda 安装的包 !!!
      - -r requirements.txt
      # 或者直接列出 pip 包:
      # - some-pip-only-package==1.0
      # - another-package>=2.1